### ISSUE TITLE
Random replays

### ISSUE THREAD

**Issue by jtotht** [mozilla/video-bg-play#13]
Since I installed this extension on desktop, while playing YouTube mixes, every now and then the current video plays twice, sometimes even more times. I think the cause might be that the extension does its work just at the end of the video. I’m certain it’s caused by this extension: I never experienced this before installing the extension, and it’s also gone when I temporarily disabled it. Any idea how to fix it?

**Comment by buttercookie42** [comment]
> YouTube mixes

Just to be sure we're both looking at the same thing, you mean e.g. the mix playlists offered by Youtube when you're e.g. looking at some music video?

> every now and then

How often is that? I listened for around half an hour in Nightly (12 videos or so, although Firefox wasn't in background all the time) and didn't notice anything strange.

> the extension does its work just at the end of the video

It doesn't actually. Events are blocked as and when they happen (but if you leave Firefox with the Youtube tab in background or foreground all the time there shouldn't be any events in the first place), the visibility API override simply returns true when Youtube asks and the user activity tracking workaround just updates a variable every few minutes.

Unfortunately I've got no idea what could cause this, especially as I cannot reproduce the issue myself.

If you feel like it, you could try temporarily disabling various parts of the add-on and see if that improves the situation.
Download [the add-on code](https://github.com/mozilla/video-bg-play/archive/master.zip) and extract it to a directory of your choice. Open [video-bg-play-content.js](https://github.com/mozilla/video-bg-play/blob/master/video-bg-play-content.js) and comment out (by placing a `/*` at the start and `*/` at the end of the bit you want to comment out) parts of the add-on:
* the [Page Visibility API](https://github.com/mozilla/video-bg-play/blob/32ed93e1a568bb42fc290f02728b6e8331226853/video-bg-play-content.js#L8-L9)
* the [visibility event blocking](https://github.com/mozilla/video-bg-play/blob/32ed93e1a568bb42fc290f02728b6e8331226853/video-bg-play-content.js#L11-L12)
* the [user activity tracking workaround](https://github.com/mozilla/video-bg-play/blob/32ed93e1a568bb42fc290f02728b6e8331226853/video-bg-play-content.js#L21-L24)

Then, you can go to _about:debugging_ and choose "Load Temporary Add-on" - just pick the version of video-bg-play-content.js you've just edited and see if you still get those issues. If yes, uncomment that block and try the next one.

**Comment by jtotht** [comment]
> > YouTube mixes
> 
> Just to be sure we're both looking at the same thing, you mean e.g. the mix playlists offered by Youtube when you're e.g. looking at some music video?

This: https://support.google.com/youtube/answer/9011078

> > every now and then
> 
> How often is that? I listened for around half an hour in Nightly (12 videos or so, although Firefox wasn't in background all the time) and didn't notice anything strange.

I haven’t counted it, but I think in average it’s not more often than once an hour.

> If you feel like it, you could try temporarily disabling various parts of the add-on and see if that improves the situation.

I started debugging, but as the bug is quite rare, I don’t have results yet.

**Comment by buttercookie42** [comment]
> This: https://support.google.com/youtube/answer/9011078

Okay, that's what I figured, too.

> but I think in average it’s not more often than once an hour.

That'll certainly won't make debugging this any easier... good luck and thank you!

**Comment by jtotht** [comment]
It seems like the page visibility API is causing the problem—I’ve commented out everything from [line 11](https://github.com/mozilla/video-bg-play/blob/32ed93e1a568bb42fc290f02728b6e8331226853/video-bg-play-content.js#L11) on, and it still occurs. If I commented out lines 8–9 and kept everything else YouTube-related, I haven’t noticed it (although, due to the nature of this issue, I can’t say it definitely hasn’t come up, but I’m quite confident).

**Comment by buttercookie42** [comment]
Thanks for the taking the time to investigate that. Given how difficult this seems to reproduce, unfortunately I probably won't have the time to find what exactly is going wrong there, but in the absence of a configuration UI (#3), maybe hard-codedly skipping the page visibility bit on Desktop Firefox might work, as it shouldn't actually be required there as long as we keep pretending that there was some user activity to avoid the "Still there?" dialogue.

**Comment by buttercookie42** [comment]
Although thinking some more, the differentiation should probably rather be desktop **Youtube** vs. mobile Youtube, rather than desktop vs. mobile Firefox...

**Comment by buttercookie42** [comment]
Sorry that it took a little while - if you're still around and still seeing these issues, could you give this test build a try please?
http://www.buttercookie.de/temp/xpi/video-bg-play-1.5b1-signed.xpi

**Comment by Ahurasim** [comment]
Hey I'm not sure if you fixed it but the Firefox addon store keeps showing your add on as corrupt and it wont download, I literally just downloaded that test build just then so hopefully thats all the same.
This is on android. Give it a peek if you can also I love this add on.

**Comment by buttercookie42** [comment]
@Ahurasim This sound like the [expired add-on certificate in Firefox](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/), so make you're running at least Firefox 66.0.5 or newer, or otherwise follow the workaround mentioned in that blog post.
If you're still having problems, open a separate issue for that please.

**Comment by Ahurasim** [comment]
Easy I used the link you sent before and I am running 66.0.2 but because I downloaded it fresh of google play the other day (After firefox patched it) and the other addons were working I assumed something had gone wrong regardless it is working now using the link also just checked and theres been an update to firefox so it'd likely work the usual way if I checked.

**Comment by buttercookie42** [comment]
Assuming this has sorted itself out, if not please let me know.

**Comment by jtotht** [comment]
I indeed haven’t experienced this issue for a while. Thanks for checking back on it!
