### ISSUE TITLE
YouTube No Longer Working

### ISSUE THREAD

**Issue by ZacharyGeorgeNN** [mozilla/video-bg-play#16]
Stopped working for YouTube this week

**Comment by buttercookie42** [comment]
Mobile or Desktop?

On Mobile (Firefox Android) I've given it a very quick try and it still seems to work, but I'll try testing it more properly at the weekend. And of course if there's a real change on Youtube's side that's broken things, it could be that it's being rolled out only gradually and hasn't reached me yet.

**Comment by ZacharyGeorgeNN** [comment]
Still works on desktop, but not mobile.

**Comment by patgiacobbe** [comment]
It popped up today on Android mobile in Firefox saying that it's an unsigned add-on and that Firefox has disabled it. I've tried to uninstalling and reinstalling and now it's saying the add-on is corrupt.

**Comment by buttercookie42** [comment]
Not the addon's fault, see https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/.

**Comment by patg84** [comment]
This is the error I'm getting on an Android from the add-ons section.

**Comment by buttercookie42** [comment]
Tried it with a playlist today, but for me everything still seems to work normally.

**Comment by CreamyCookie** [comment]
Background play works. Autoplay doesn't work on Android.

**Comment by krystian3w** [comment]
https://greasyfork.org/en/scripts/371641-video-background-play-fix/code

Maybe works better as addon?

**Comment by buttercookie42** [comment]
Cannot reproduce this issue.
