### ISSUE TITLE
Not compatible with 75.0.0-beta.6 (Android)

### ISSUE THREAD

**Issue by cen1** [mozilla/video-bg-play#20]
After updating to the specified version the extension became incompatible.

Play Store, Firefox Beta program.

**Comment by buttercookie42** [comment]
At the moment only a few selected add-ons from the "Recommended Extensions" programme are allowed in the rewritten version of Firefox for Android, and somewhat ironically this extension was dropped from that programme because at the time, addons.mozilla.org apparently had some technical difficulties with supporting Android-only extensions as "Recommended extensions".

**Comment by cen1** [comment]
Is this just a temporary Beta thing or will it also affect the stable release? I can survive not having this in Beta (I will just switch to stable) although ironically, I installed it specifically to report and give feedback on pre-release bugs not to be sabotaged by Mozilla with extension whitelists..

**Comment by buttercookie42** [comment]
Given that this is a simple content script without any UI, I wouldn't expect any major incompatibilities, though I will try to see if there's a way to at least temporarily load the add-on for testing purposes in Nightly or something like that to check it out.

> Is this just a temporary Beta thing or will it also affect the stable release?

The latest official announcement [was this one](https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/), so no idea - I'd be pleasantly surprised if they get to the stage of general add-on availability before pushing the rewrite to the Release channel, but it's equally not inconceivable that general add-on support will be among the features still missing when the transition happens.

**Comment by gwarser** [comment]
If someone really need a workaround, then this add-on functionality can probably be converted to uBO scriptlet. Simpler version based on ["Disable Page Visibility API"](https://addons.mozilla.org/firefox/addon/disable-page-visibility/):

    https://gist.githubusercontent.com/gwarser/3b47b61863bffcfebe4498c77b2301cd/raw/disable-pageview-api.js

Add above link to `userResourcesLocation` uBO [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings) and add `youtube.com##+js(disable-pageview-api)` filter to "My filters".

**Comment by buttercookie42** [comment]
(Though that doesn't help against Youtube stopping playback anyway if there's no detected user activity within a certain time frame)

**Comment by robsmith11** [comment]
This link to the ublock script is broken.  Could someone paste it here?

I have to keep an old version of Fennec installed just so I can use this add on..

**Comment by gwarser** [comment]
> This link to the ublock script is broken.

How?

Host it somewhere else:

```
/// disable-pageview-api.js
// Based on: https://addons.mozilla.org/firefox/addon/disable-page-visibility/
// License:  http://www.opensource.org/licenses/bsd-license.php
(function(){
// visibilitychange events are captured and stopped 
document.addEventListener("visibilitychange", function(e) {
    e.stopImmediatePropagation();
}, true);
// document.visibilityState always returns false
Object.defineProperty(Document.prototype, "hidden", {
    get: function hidden() {
        return false;
    },
    enumerable: true,
    configurable: true
});
// document.visibilityState always returns "visible"
Object.defineProperty(Document.prototype, "visibilityState", {
    get: function visibilityState() {
        return "visible";
    },
    enumerable: true,
    configurable: true
});
})()
```

**Comment by lpd-au** [comment]
> At the moment only a few selected add-ons from the "Recommended Extensions" programme are allowed in the rewritten version of Firefox for Android, and somewhat ironically this extension was dropped from that programme because at the time, addons.mozilla.org apparently had some technical difficulties with supporting Android-only extensions as "Recommended extensions".

Have you considered filing a bug in the fenix repo? If it's true that this used to be a recommended extension and was later only dropped for technical reasons, perhaps they'd consider making it one of the whitelisted extensions, especially given the minimal work required to support it.

**Comment by charlieethan** [comment]
I have opened an issue 2 months ago in fenix : [#10366](https://github.com/mozilla-mobile/fenix/issues/10366), they didn't close it and I think that maybe within 1 month, they will decide how to solve the problem about "video play in the background", even if they don't use this Add-on

**Comment by aroskuski** [comment]
Unfortunately even with this add-on forcibly installed via `web-ext` it seems like YouTube still periodically stops when in the background. Seems likely that mozilla-mobile/fenix#9691 is the culprit.

**Comment by pablo-hp** [comment]
Without this extension, I will use Edge or Chrome.

**Comment by cen1** [comment]
@aroskuski any instructions to force install this on mobile?

**Comment by aroskuski** [comment]
@cen1 `web-ext run` _can_ temporarily install it over USB debugging using the `--target=firefox-android` flag, but it will disappear the next time Firefox has to restart (which can be pretty often on Android).  It's really not super useful aside from doing some quick tethered testing.  You can find some documentation on using `web-ext` [here](https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/) if you really want to to try, but I suspect you'll probably want to wait for a slightly more permanent solution.

**Comment by OrionRed** [comment]
> If someone really need a workaround, then this add-on functionality can probably be converted to uBO scriptlet. Simpler version based on ["Disable Page Visibility API"](https://addons.mozilla.org/firefox/addon/disable-page-visibility/):
> 
> ```
> https://gist.githubusercontent.com/gwarser/3b47b61863bffcfebe4498c77b2301cd/raw/disable-pageview-api.js
> ```
> 
> Add above link to `userResourcesLocation` uBO [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings) and add `youtube.com##+js(disable-pageview-api)` filter to "My filters".

This seems to work for about 60 seconds. I'm wondering if my settings are refreshing the page every minute, or if YouTube is set to reload the page after 60 seconds to keep this from working. It would be a way to push people to YouTube Red.

**Comment by aroskuski** [comment]
> > If someone really need a workaround, then this add-on functionality can probably be converted to uBO scriptlet. Simpler version based on ["Disable Page Visibility API"](https://addons.mozilla.org/firefox/addon/disable-page-visibility/):
> > ```
> > https://gist.githubusercontent.com/gwarser/3b47b61863bffcfebe4498c77b2301cd/raw/disable-pageview-api.js
> > ```
> > 
> > 
> > Add above link to `userResourcesLocation` uBO [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings) and add `youtube.com##+js(disable-pageview-api)` filter to "My filters".
> 
> This seems to work for about 60 seconds. I'm wondering if my settings are refreshing the page every minute, or if YouTube is set to reload the page after 60 seconds to keep this from working. It would be a way to push people to YouTube Red.

As I mentioned above, seems like a pretty good chance this is a manifestation of mozilla-mobile/fenix#9691

**Comment by PtrckDns** [comment]
> > If someone really need a workaround, then this add-on functionality can probably be converted to uBO scriptlet. Simpler version based on ["Disable Page Visibility API"](https://addons.mozilla.org/firefox/addon/disable-page-visibility/):
> > ```
> > https://gist.githubusercontent.com/gwarser/3b47b61863bffcfebe4498c77b2301cd/raw/disable-pageview-api.js
> > ```
> > 
> > 
> > Add above link to `userResourcesLocation` uBO [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings) and add `youtube.com##+js(disable-pageview-api)` filter to "My filters".
> 
> This seems to work for about 60 seconds. I'm wondering if my settings are refreshing the page every minute, or if YouTube is set to reload the page after 60 seconds to keep this from working. It would be a way to push people to YouTube Red.

Found a workaround using Firefox beta, access about:config and change "dom.suspend_inactive.enabled" to false

**Comment by robsmith11** [comment]
Thanks! The combination of the ublock filter and the about:config field worked for me.  Youtube works for an hour with the screen off.  I can finally uninstall Fennec :)

**Comment by buttercookie42** [comment]
Now apparently officially installable on Nightly (I had suggested to hold off on that until the Firefox could be resolved so users wouldn't end up with an effectively still broken add-on, but whatever – at least this issue is out of the way I guess)
