### ISSUE TITLE
It pauses the video in the background after 60 secs

### ISSUE THREAD

**Issue by PtrckDns** [mozilla/video-bg-play#22]
In the new Firefox version 79.0.5 it pauses the video after 60 secs or less while playing in the background

**Comment by pablo-hp** [comment]
Without this extension, I will use Edge or Chrome.

**Comment by JoGarWeb** [comment]
Change to Beta version or Nigthly Version, enter to about:config and change "dom.suspend_inactive.enabled" to false.

**Comment by PtrckDns** [comment]
> Change to Beta version or Nigthly Version, enter to about:config and change "dom.suspend_inactive.enabled" to false.

Yeah saw it on reddit as well, using Firefox beta for a week now.

**Comment by Poopooracoocoo** [comment]
> Without this extension, I will use Edge or Chrome.

Why not browsers that include this like Brave or Bromite?

**Comment by conkerts** [comment]
I switched now to Brave. Solved the Problem.
Maybe when Mozilla will end up with few Users left, they will get their shit together again.

**Comment by buttercookie42** [comment]
I think the original Firefox issues have since been resolved.
