### ISSUE TITLE
Make extension available for sideloading

### ISSUE THREAD

**Issue by thiagoeh** [mozilla/video-bg-play#23]
After Mozilla latest Firefox for Android update, and the mass disabling of extensions, I migrated to Fennec.
Even though, the extension is not available for download in Mozilla's extensions page.
Could you please make it available for sideloading? Maybe using Github releases feature.

Thank you for your work!

**Comment by PtrckDns** [comment]
Can you use uBlock origin on Fennec?

**Comment by buttercookie42** [comment]
The "Add to Firefox" button on AMO is in fact a normal link, so long-pressing it and then opening it in a new tab/manually copying the address/... should still work to get the XPI.
