### ISSUE TITLE
Doesn't install on android

### ISSUE THREAD

**Issue by hildogjr** [mozilla/video-bg-play#27]
It doesn't install on Firefox android anymore.

**Comment by rpattabi** [comment]
The add-on is currently broken due to https://github.com/mozilla-mobile/fenix/issues/9691. That may be the reason it is not available now. Good news is that the bug is fixed in firefox beta.

**Comment by PranavBhattarai** [comment]
I'm using Firefox 82.1.1 and it installs fine. 
What are we talking about!?

This need to closed if I'm not wrong.

**Comment by hildogjr** [comment]
It was not installing in Firefox 81. Recently Firefox Android 82+ extended the supported plugins.
