### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by hugurp** [mozilla/video-bg-play#29]
Hello,

First, thanks for this addon! Most useful I've got with ublock origin.

Also not a iOS user myself, I am wondering what prevent this bit of code to work in Firefox for iOS?

Cheers

**Comment by buttercookie42** [comment]
> what prevent this bit of code to work in Firefox for iOS?

The fact that Firefox on iOS doesn't support add-ons for a start? (Which might or might not also be blamed on Apple's overly restrictive app store policies, but either way there's nothing I can do about that…)

Technically, there's also the fact the code currently assumes it's only ever being run in a Gecko-based browser (using `wrappedJSObject` for a start), but it could probably easily be fixed and in any case it doesn't really matter in view of the first problem.

**Comment by hugurp** [comment]
Thanks for the answer and overview on the situation.
I am trying to understand if the method used by this addon could be used cross-platform to prevent the same events from stopping the playback cross platform with such bit of javascript https://github.com/internet4000/radio4000-player
Will continue to investigate,
Cheers!
