### ISSUE TITLE
Can't install this addon

### ISSUE THREAD

**Issue by xmha97** [mozilla/video-bg-play#30]
Why I can't install this addon?
![Firefox](https://user-images.githubusercontent.com/23485114/111804040-efadd500-88e4-11eb-886c-2fd0d922340f.png)

**Comment by gwarser** [comment]
Try this link https://addons.mozilla.org/en-US/android/addon/video-background-play-fix/

**Comment by xmha97** [comment]
Thanks for your guidance, I installed the extension but it does not work for instagram.com
I recommend the following extension: https://addons.mozilla.org/en-US/firefox/addon/disable-page-visibility/

**Comment by buttercookie42** [comment]
There was some weirdness regarding the recommended extensions programme and the add-ons whitelist for Android, so the last version was marked as being for Android only. Unfortunately it seems that AMO doesn't handle this situation (latest version is only for Android, older versions are for both desktop and Android) very well, but there's a small update for Youtube due soon, anyway, so I'll mark that one as compatible for desktop once more. As for Instagram, see #19.
