### ISSUE TITLE
Please add a PIP fix for YouTube. 

### ISSUE THREAD

**Issue by Ksanbah** [mozilla/video-bg-play#38]
The Picture-in-picture mode does not work for the website, and I honestly don't know who could fix it better than you guys. This add-on is a fix for video background audio, but maybe you could add a PIP fix for YouTube. Please consider. Thank you :)

**Comment by claudiu64** [comment]
@Ksanbah If you have Firefox Mobile Browser, the problem is known and will be fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1827583

**Comment by Ksanbah** [comment]
Noted Tk U.
