### ISSUE TITLE
Fix YouTube TV

### ISSUE THREAD

**Issue by Madis0** [mozilla/video-bg-play#4]
The [YouTube TV ](youtube.com/tv) site has recently implemented a similar feature where switching tabs pauses the video. I have tried several extensions that promise to block the Page Awareness API, but with no luck, so I assume they use additional measures to do this. 

Perhaps you have any ideas on how to fix it.

**Comment by buttercookie42** [comment]
Same question as in #5: Is this still required?

**Comment by Madis0** [comment]
For me, YouTube TV background playback works with the extension v1.4.
