### ISSUE TITLE
Playback in background stops after a few minutes

### ISSUE THREAD

**Issue by gohan2091** [mozilla/video-bg-play#45]
Please read the reviews on the Mozilla Extensions page because your fantastic extension is broken and we would really like it fixed if possible please: https://addons.mozilla.org/en-GB/firefox/addon/video-background-play-fix/reviews/

**Comment by buttercookie42** [comment]
Found a possible Firefox issue, which would explain it at least for playlists:
https://bugzilla.mozilla.org/show_bug.cgi?id=1878115

Does that (i.e. playing back lots of smaller tracks in background, not one single long video) fit your observations?

**Comment by gohan2091** [comment]
> Found a possible Firefox issue, which would explain it at least for playlists: https://bugzilla.mozilla.org/show_bug.cgi?id=1878115
> 
> Does that (i.e. playing back lots of smaller tracks in background, not one single long video) fit your observations?

I don't watch/listen to playlists though. I am on Youtube.com (usually the mobile version) and it happens with single videos. It also happens on other websites with videos. I just want to have podcasts playing in the background or conversational videos with the screen off (to save battery) while I cook and do chores.

**Comment by buttercookie42** [comment]
Hm. The problem is that it's somewhat hard to disambiguate between some change on Youtube's side which is only gradually rolling out and which I might not be seeing yet [1], a bug in Firefox and/or some Android manufacturers being over-eager in killing background apps.

How willing/able/comfortable would you be with trying to use ADB for attempting to figure out what is going on? I can try providing some guidance as far as possible.

[1] Yesterday I've been able to playback a 25 min video in background without problems – the aforementioned Firefox bug only seems to happen after switching to a new video while in background, whether through playlists, or presumably also letting Youtube automatically play the next video after the first one.

**Comment by gohan2091** [comment]
> Hm. The problem is that it's somewhat hard to disambiguate between some change on Youtube's side which is only gradually rolling out and which I might not be seeing yet [1], a bug in Firefox and/or some Android manufacturers being over-eager in killing background apps.
> 
> How willing/able/comfortable would you be with trying to use ADB for attempting to figure out what is going on? I can try providing some guidance as far as possible.
> 
> [1] Yesterday I've been able to playback a 25 min video in background without problems – the aforementioned Firefox bug only seems to happen after switching to a new video while in background, whether through playlists, or presumably also letting Youtube automatically play the next video after the first one.

Sorry I have no idea what ADB is but this problem is not just affecting me alone, if you read the reviews on the extension on Mozilla site there are many having the same issue. Heres my workflow to reproduce the error:

1) Open Firefox and go to the mobile version of Youtube, I believe it's m.youtube.com
2) Open and play any video
3) Turn screen off
4) Video continues to play for around 5 minutes then abruptly stops
5) Turn screen back on
6) Watch Firefox page automatically reload on it's own and the video seek bar resets to 0:00 (the start)

You can swap step 3 with "minimise Firefox and do something else on the phone like play a game or read Facebook/X/Telegram posts on their individual apps. The video playback will stop on it's own after around 5 minutes.

**Comment by buttercookie42** [comment]
Does that happen even with Firefox Nightly?

**Comment by gohan2091** [comment]
> Does that happen even with Firefox Nightly?

I don't use Firefox Nightly but I've update Firefox whenever there is an update and there has been a few over the last couple of weeks.

**Comment by buttercookie42** [comment]
I've tested it with both a current Nightly as well as the current release (version 122), and the only thing I can reproduce is the issue I linked to above – if I use a playlist or autoplay to play back *multiple* videos, then at some point after the second video has started, Firefox gets killed by Android.

However the first video always works fine, even if it's a half-hour episode of some radio comedy or whatever.

So if what people are seeing is really happening with a single video and no autoplay involved, then like I said: Either Youtube is gradually rolling out/testing a behaviour change that I'm not yet seeing, or else it's some sort of Firefox and/or Android issue which doesn't happen on my own phone. (Out of curiosity, what phone and Android version are you on?) Without any logs, unfortunately I can't say more than that…

**Comment by gohan2091** [comment]
> I've tested it with both a current Nightly as well as the current release (version 122), and the only thing I can reproduce is the issue I linked to above – if I use a playlist or autoplay to play back _multiple_ videos, then at some point after the second video has started, Firefox gets killed by Android.
> 
> However the first video always works fine, even if it's a half-hour episode of some radio comedy or whatever.
> 
> So if what people are seeing is really happening with a single video and no autoplay involved, then like I said: Either Youtube is gradually rolling out/testing a behaviour change that I'm not yet seeing, or else it's some sort of Firefox and/or Android issue which doesn't happen on my own phone. (Out of curiosity, what phone and Android version are you on?) Without any logs, unfortunately I can't say more than that…

It's not a situation unique to Youtube. As I said, other video platforms it also happens as well such as X (Twitter) in the Firefox browser and Rumble. This is not an issue unique to me, others on the review comments have stated the same.

I am on Android version 12 on a Samsung Galaxy Note 10+ 5G. I have preordered a Samsung Galaxy S24 Ultra which is due to arrive in the next week and a half so I will certainly try on the new phone.

**Comment by GtG6969** [comment]
I dont think the app developers for this receive and sort of financial compensation  to build and maintain this program. Report the issue accurately and if they are able to fix great, if not dont be dramatic or act like they are supposed to or even need to do anything. Everyone willing to preorder this app for 2 or 3 dollars and im sure the be more then happy to spend time with updates.  Sorry for rant but i see this all over and just seems funny how unaware of how much time it can take to fix even minor issues.  Apologies for the rant 👽

**Comment by gohan2091** [comment]
Happening on my new phone now just FYI.

**Comment by gohan2091** [comment]
> I dont think the app developers for this receive and sort of financial compensation to build and maintain this program. Report the issue accurately and if they are able to fix great, if not dont be dramatic or act like they are supposed to or even need to do anything. Everyone willing to preorder this app for 2 or 3 dollars and im sure the be more then happy to spend time with updates. Sorry for rant but i see this all over and just seems funny how unaware of how much time it can take to fix even minor issues. Apologies for the rant 👽

I mean why even bother for any developer to create anything for anyone? This is a very useful extension loved by lots. The developer(s) obviously want to share their work with other people so if it no longer is working for some, I would expect they would be keen to try and fix it because the extension is their creation and they want to continue sharing it.

**Comment by ttapk** [comment]
Same issue on my Xiaomi 12 (Android 13, MIUI 14)

**Comment by buttercookie42** [comment]
I've re-tested, but I'm afraid I still can't reproduce the issue. Without any logs I can't say anything further about what might be happening.

**Comment by gohan2091** [comment]
> I've re-tested, but I'm afraid I still can't reproduce the issue. Without any logs I can't say anything further about what might be happening.

Go to sites like Rumble and Youtube, click a video, let it run for 10 minutes + with the screen turned off. If your device is not stopping and the page is not reloading then I would love to know why. Both my Samsung android phones do this. I hope one day we can find out the cause as it's very annoying. For now, I have disabled the extension. Thanks for your efforts.

**Comment by gwarser** [comment]
https://dontkillmyapp.com/ ?

**Comment by buttercookie42** [comment]
This add-on doesn't even do anything on Rumble, and I still think it's most likely some combination of Android and/or Firefox issues. If somebody wants to do some more investigating and knows how to use [ADB](https://developer.android.com/tools/releases/platform-tools):

After you've started playback, look at _about:processes_ and note down the ID of both the main process ("Firefox") or whatever, and the "Shared Web Process" that is hosting the background playback, i.e. which has Youtube or whatever loaded. Then,

a) periodically check the output of _adb shell dumpsys meminfo_. Look at the end where it lists "Total PSS by OOM adjustment:" and check in which category (Foreground/Visible/Perceptible/…/Cached) the respective Firefox Processes are listed. If either of the two processes you've noted down above ends up as "Cached", that's a clear sign that something is going wrong.
b) Run _adb logcat_ and filter for the process IDs you've noted down above. If/when playback suddenly stops, check if there are any messages about a Firefox process having been killed.

And [file a Firefox bug](https://bugzilla.mozilla.org/enter_bug.cgi) with the above info.

**Comment by gwarser** [comment]
> doesn't even do anything on Rumble

Because it only works on YT and Vimeo.

**Comment by gohan2091** [comment]
> > https://dontkillmyapp.com/ ?
> 
> Oh this looks very interesting! I will check it out. Thank you!

I don't know if it's the app itself or the advice given by the app/website regarding battery saving features but I turned off everything I could find about battery and power saving for Firefox and now I am able to turn off my screen (with this plugin enabled) and the audio continues to play and it does not stop and reload the page by itself. So problem solved! thanks very much for that post. It looks like the extension is working fine and it's to do with Android power saving features!
