### ISSUE TITLE
Add YouTube Music support

### ISSUE THREAD

**Issue by TruongTanLuc201270** [mozilla/video-bg-play#46]
Press home button stopped playback but I fix pull notification player press play to run.

**Comment by buttercookie42** [comment]
Hi,

is there some way to reproduce the issue without a Youtube Music 
subscription? (And wasn't the point of a Youtube Music subscription to 
officially let you listen in background anyway?) Can you give a specific 
example of what song/video isn't working?

**Comment by TruongTanLuc201270** [comment]
https://github.com/mozilla/video-bg-play/assets/145727083/b6b3ff8a-7533-42b2-a9a5-c7bafcab5721

Without YouTube Premium, can be playable.
This fixed by install this extension.
