### ISSUE TITLE
extension appears to prevent phone calls interrupting media playback

### ISSUE THREAD

**Issue by isthisrubble** [mozilla/video-bg-play#47]
I've recently installed this extension on my phone (samsung s10e), and while it seems to work fine, I just had a call where there was no interruption of the youtube video so the phone could audibly ring. I was not looking at the phone when it happened, so missed the call. I haven't had the chance to try to replicate this (can't ask anyone to call me atm) but thought I should report it before I forgot.

if you think this is a me/phone setting issue, please let me know.

**Comment by buttercookie42** [comment]
Handling audio focus with regard to other Android apps is Firefox's responsibility, so this is [probably a Firefox issue](https://bugzilla.mozilla.org/enter_bug.cgi?product=Fenix).

It's possible that without this extension an incoming phone call would put Firefox into the background, causing Youtube to pause itself, but in that case that'd be only masking a pre-existing Firefox bug. Both websites and this extension can't distinguish *why* a tab has been put into the background, so I can't do anything to treat phone calls specially – that's Firefox's responsibility.
