### ISSUE TITLE
Extension does not work on Xiaomi 14 running hyperos

### ISSUE THREAD

**Issue by alytaleb** [mozilla/video-bg-play#48]
When I lock the screen, YouTube playback stops immediately when running on a Xiaomi 14 using Hyperos. I used to have different Samsung phones (S10, S20, Flip 5) and it worked without any issues

**Comment by buttercookie42** [comment]
That's a Xiaomi issue then, there's nothing the add-on can do about OS level stuff. Maybe try if anything from [https://dontkillmyapp.com/xiaomi](https://dontkillmyapp.com/xiaomi) works, otherwise you're on your own, sorry.

**Comment by alytaleb** [comment]
The steps on https://dontkillmyapp.com/xiaomi actually worked. Thanks!!
