### ISSUE TITLE
Next/Back Forward Revere controls

### ISSUE THREAD

**Issue by CallmeDefender** [mozilla/video-bg-play#49]
Next/Back Forward Revere controls not showing in notification panel kindly add this feature to play next song from notification panel rather then open browser to forward song or play next song

**Comment by CallmeDefender** [comment]
![Screenshot_20240923-141412_Firefox](https://github.com/user-attachments/assets/03ba1bb6-61e6-4b4f-9cc6-5b82a8fe8bf5)

**Comment by buttercookie42** [comment]
That's probably a Firefox issue, [please report it here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Fenix).
