### ISSUE TITLE
Youtube background stops after a while

### ISSUE THREAD

**Issue by whitevo** [mozilla/video-bg-play#7]
Last week I got a new phone (Huawei Honor 10, COL-AL10) which has a newer Android version, 8.1.0
I downloaded the same addon, the firefox does play on background, but after a few songs, it stops.
When I unlock the phone again sometimes it starts playing next song (and I don't even have to open firefox)
But sometimes Youtube in Firefox shows this error "Invalid Response Received"

I looked around my phone, I found a setting which stated that screen off disables some WLAN connections, I disabled it.
Under battery management disabled all savings.
After these change, it still does not work.

There is an app called "stay alive", which is supposed to keep connections alive, but even that does not work and as soon as the phone goes sleep, no more connections pass through.

Currently, I am using an app "touch protector" to keep the screen alive.

Is there some way for your app to disable some settings what I as the user can't change so that my phone never loses connections?
Or my only option is to change Huawei software?
And can I even run for example Pixel 2 software on Huawei or every phone has to have its own software compatible with firmware?

**Comment by buttercookie42** [comment]
This extension is only intended for the case where a web site itself blocks background playback. It cannot influence anything that's happening between Firefox and Android. Regarding manufacturers that use some overzealous power optimisation "features" (which apparently includes Huawei), even Firefox itself won't be able to change that kind of system settings.

> Under battery management disabled all savings.

Was there any option to whitelist specific apps, and did you try whitelisting Firefox specifically?

> And can I even run for example Pixel 2 software on Huawei or every phone has to have its own software compatible with firmware?

Each phone model requires its own customised firmware. [Some googling ](https://www.google.com/search?q=COL-AL10+LineageOS&ie=utf-8&oe=utf-8&client=firefox-b-ab) suggests that [LineageOS builds _are_ available](https://www.getdroidtips.com/lineage-os-15-1-honor-10/) for your phone, but installing a custom ROM shouldn't be done casually without knowing what you're doing and I cannot give you any further help there. Good luck, though...
