### ISSUE TITLE
Addon causes 90% of video to be covered with black window after returning from fullscreen

### ISSUE THREAD

**Issue by robsmith11** [mozilla/video-bg-play#8]
The addon still works great for playing Youtube videos in the background, but for the past month or so with Fennec Nightly, when I leave fullscreen in portrait orientation, the top 90% of the video will be covered by a black window.

The issue does not  occur if I disable the video-bg-play addon.

**Comment by buttercookie42** [comment]
Fixed in 0b3197b8411002a333cb0a657b1574183cef12b1.
